-- Demo marketplace owners: 8 accounts that own the seeded listings.
--
-- Generated by supabase/seed/demo_marketplace/build-sql.mjs - edit owners.json and
-- re-run it instead of editing this file. NOT a migration: run it by hand (Supabase
-- SQL editor, psql or the Supabase MCP), then run seed.ts to create the locations,
-- the listings and the photos as these owners.
--
-- Profiles are tagged [demo_marketplace] so the cleanup block at the bottom is exact.

do $$
declare
  demo_password text := 'SeedDemo2026!';
  accounts jsonb := $json$[{"email":"demo.marko@snd.rs","first_name":"Marko","last_name":"Petrović","display_name":"Marko P.","about":"Iznajmljujem alat i opremu koju koristim na gradilištu. Preuzimanje na Vračaru ili Zvezdari."},{"email":"demo.jelena@snd.rs","first_name":"Jelena","last_name":"Ilić","display_name":"Jelena I.","about":"Foto i video oprema iz mog studija. Sve je servisirano i spremno za snimanje."},{"email":"demo.nikola@snd.rs","first_name":"Nikola","last_name":"Jovanović","display_name":"Nikola J.","about":"Bašta, dvorište i sve za roštilj. Javite se dan ranije da pripremim opremu."},{"email":"demo.ana@snd.rs","first_name":"Ana","last_name":"Marković","display_name":"Ana M.","about":"Dečija oprema i kućni aparati. Sve redovno čistim i proveravam pre izdavanja."},{"email":"demo.stefan@snd.rs","first_name":"Stefan","last_name":"Nikolić","display_name":"Stefan N.","about":"Oprema za kampovanje i planinarenje. Vikendom sam dostupan i za rano preuzimanje."},{"email":"demo.milica@snd.rs","first_name":"Milica","last_name":"Pavlović","display_name":"Milica P.","about":"Muzička i studijska oprema. Rado objasnim kako se sve povezuje pre preuzimanja."},{"email":"demo.dusan@snd.rs","first_name":"Dušan","last_name":"Stanković","display_name":"Dušan S.","about":"Prikolice, krovni nosači i građevinska mehanizacija. Moguć dogovor i za duži period."},{"email":"demo.ivana@snd.rs","first_name":"Ivana","last_name":"Ristić","display_name":"Ivana R.","about":"Oprema za proslave i svečane prilike. Dogovor oko dostave je uvek moguć."}]$json$::jsonb;
  account jsonb;
  owner_uid uuid;
begin
  for account in select value from jsonb_array_elements(accounts) loop
    select id into owner_uid from auth.users where email = account ->> 'email';

    if owner_uid is null then
      owner_uid := gen_random_uuid();

      -- GoTrue reads the token columns into plain strings, so they have to be
      -- empty rather than NULL or every sign-in fails with a schema error.
      insert into auth.users (
        instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, recovery_token, email_change_token_new,
        email_change_token_current, email_change, phone_change, phone_change_token,
        reauthentication_token
      )
      values (
        '00000000-0000-0000-0000-000000000000', owner_uid, 'authenticated', 'authenticated',
        account ->> 'email', crypt(demo_password, gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
        '', '', '', '', '', '', '', ''
      );

      insert into auth.identities (
        id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
      )
      values (
        gen_random_uuid(), owner_uid::text, owner_uid,
        jsonb_build_object(
          'sub', owner_uid::text, 'email', account ->> 'email',
          'email_verified', true, 'phone_verified', false
        ),
        'email', now(), now(), now()
      );
    else
      -- Re-running the seed must leave the account signable-in with the same password.
      update auth.users
      set encrypted_password = crypt(demo_password, gen_salt('bf')),
          email_confirmed_at = coalesce(email_confirmed_at, now())
      where id = owner_uid;
    end if;

    -- Publishing is gated on public.users.email_verified_at, not on auth.
    update public.users
    set email_verified_at = coalesce(email_verified_at, now()), status = 'active'
    where id = owner_uid;

    update public.user_profiles
    set first_name = account ->> 'first_name',
        last_name = account ->> 'last_name',
        display_name = account ->> 'display_name',
        about = (account ->> 'about') || ' [demo_marketplace]',
        country_code = 'RS',
        updated_at = now()
    where user_id = owner_uid;
  end loop;
end;
$$;

-- Undo (drops the listings and photos with the accounts):
--
-- delete from storage.objects where bucket_id = 'listing-images'
--   and (storage.foldername(name))[1]::uuid in (
--     select id from public.listings where owner_id in (
--       select id from auth.users where email like 'demo.%@snd.rs'));
-- delete from public.listings where owner_id in (
--   select id from auth.users where email like 'demo.%@snd.rs');
-- delete from auth.users where email like 'demo.%@snd.rs';
