// Turns owners.json into the account half of the seed (demo_marketplace_users.sql).
// Only the auth accounts need admin rights; locations, listings and photos are
// created by seed.ts as the owners themselves, over the public API.
// Run: node supabase/seed/demo_marketplace/build-sql.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const owners = JSON.parse(readFileSync(resolve(here, 'owners.json'), 'utf8'))

const accounts = owners.map((owner) => ({
  email: owner.email,
  first_name: owner.first_name,
  last_name: owner.last_name,
  display_name: owner.display_name,
  about: owner.about,
}))

const sql = `-- Demo marketplace owners: ${accounts.length} accounts that own the seeded listings.
--
-- Generated by supabase/seed/demo_marketplace/build-sql.mjs - edit owners.json and
-- re-run it instead of editing this file. NOT a migration: run it by hand (Supabase
-- SQL editor, psql or the Supabase MCP), then run seed.ts to create the locations,
-- the listings and the photos as these owners.
--
-- Profiles are tagged [demo_marketplace] so the cleanup block at the bottom is exact.

do $$
declare
  demo_password text := 'SeedDemo2026!';
  accounts jsonb := $json$${JSON.stringify(accounts)}$json$::jsonb;
  account jsonb;
  owner_uid uuid;
begin
  for account in select value from jsonb_array_elements(accounts) loop
    select id into owner_uid from auth.users where email = account ->> 'email';

    if owner_uid is null then
      owner_uid := gen_random_uuid();

      -- GoTrue reads the token columns into plain strings, so they have to be
      -- empty rather than NULL or every sign-in fails with a schema error.
      insert into auth.users (
        instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
        confirmation_token, recovery_token, email_change_token_new,
        email_change_token_current, email_change, phone_change, phone_change_token,
        reauthentication_token
      )
      values (
        '00000000-0000-0000-0000-000000000000', owner_uid, 'authenticated', 'authenticated',
        account ->> 'email', crypt(demo_password, gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
        '', '', '', '', '', '', '', ''
      );

      insert into auth.identities (
        id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
      )
      values (
        gen_random_uuid(), owner_uid::text, owner_uid,
        jsonb_build_object(
          'sub', owner_uid::text, 'email', account ->> 'email',
          'email_verified', true, 'phone_verified', false
        ),
        'email', now(), now(), now()
      );
    else
      -- Re-running the seed must leave the account signable-in with the same password.
      update auth.users
      set encrypted_password = crypt(demo_password, gen_salt('bf')),
          email_confirmed_at = coalesce(email_confirmed_at, now())
      where id = owner_uid;
    end if;

    -- Publishing is gated on public.users.email_verified_at, not on auth.
    update public.users
    set email_verified_at = coalesce(email_verified_at, now()), status = 'active'
    where id = owner_uid;

    update public.user_profiles
    set first_name = account ->> 'first_name',
        last_name = account ->> 'last_name',
        display_name = account ->> 'display_name',
        about = (account ->> 'about') || ' [demo_marketplace]',
        country_code = 'RS',
        updated_at = now()
    where user_id = owner_uid;
  end loop;
end;
$$;

-- Undo (drops the listings and photos with the accounts):
--
-- delete from storage.objects where bucket_id = 'listing-images'
--   and (storage.foldername(name))[1]::uuid in (
--     select id from public.listings where owner_id in (
--       select id from auth.users where email like 'demo.%@snd.rs'));
-- delete from public.listings where owner_id in (
--   select id from auth.users where email like 'demo.%@snd.rs');
-- delete from auth.users where email like 'demo.%@snd.rs';
`

writeFileSync(resolve(here, '..', 'demo_marketplace_users.sql'), sql)
console.log(`wrote demo_marketplace_users.sql (${accounts.length} accounts)`)
